### PR TITLE
Merge in 1.4 branch updates from upstream

### PR DESCRIPTION
**Pull request by iramiller**

### CODE REVIEW

**Comment by mtps** [comment]
That's a huge diff. One thing noted, they have kafka -> raft migrations code available now to migrate the consensus over.

**Comment by iramiller** [comment]
We might want to do this sync more often I think ... I wasn't expecting this much work on the release branch ... but I guess they plan to do all the point release stuff on here...

**Comment by mtps** [comment]
Is this something we could leverage jenkins to sync a clean merge?

**Comment by iramiller** [comment]
Not sure about Jenkins automating this process... I like the PR to review what is happening upstream... it would probably be nice to have PRs automatically filed at some interval or based on upstream published changes though...

**Pull request merged**
